close all;
clear;
I=imread('lake.jpg');
[m,n,l]=size(I);
h=rgb2hsv(I);
% I(:,:,3);
% H2=h(:,:,2);
mask=(h(:,:,1)<0.8)+(h(:,:,2)>0.65);
S=h(:,:,2).*(1-mask);
h(:,:,2)=S;
% figure;
% imshow(h);
level=graythresh(h);
BW=im2bw(I,level);
L=bwlabel(1-BW);
% figure;
% imshow(L);
figure;
subplot(1,2,1);
imshow(I);
subplot(1,2,2);
I_(:,:,1)=zeros(m,n);
I_(:,:,2)=zeros(m,n);
I_(:,:,3)=zeros(m,n);
I_(:,:,1)=double(I(:,:,1)).*L;
I_(:,:,2)=double(I(:,:,2)).*L;
I_(:,:,3)=double(I(:,:,3)).*L;
I_=I_(:,:,2).*mask;
imshow(I_);

